language: node_js

node_js:
  - 'lts/*'

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: "Lint"
      script:
        - npm run lint -- --quiet
        - npm run lint:fix
    - stage: "Test"
      script:
        - npm test
    - stage: "Sync"
      if: branch = master AND type != pull_request
      script:
        - git remote add gitlab https://oauth2:$GITLAB_TOKEN@gitlab.fdmci.hva.nl/desqol/mycoeliac.git
        - git push --force gitlab --all
        - git push --force gitlab --tags
