language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: "Lint"
      script:
        - npm run lint
        - npm run lint:fix
    - stage: "Test"
      script:
        - npm test
    - stage: "Sync"
      if: branch = master
      script:
        - git remote add gitlab https://oauth2:$GITLAB_TOKEN@gitlab.fdmci.hva.nl/desqol/mycoeliac.git
        - git push --force gitlab --all
        - git push --force gitlab --tags
